### ISSUE TITLE
Sponsor logos

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#22] opened 2019-07-30 18:42 UTC
@autumnfound - Hi Martin, can you take look a resizing the sponsor logos so their closer to the same size pls?  In particular, the CORE-V logo looks a little big...

**Comment by chrisguindon** [comment] 2019-07-30 18:53
@autumnfound I think the logos would look better if you remove the width on each img and set a max-width of about 77px.

![Screen Shot 2019-07-30 at 2 51 33 PM](https://user-images.githubusercontent.com/893942/62156794-b375cd00-b2d9-11e9-8b56-b6935638a1dc.png)

Would this work for you @rickoco?

**Comment by rickoco** [comment] 2019-07-31 17:48
@chrisguindon @autumnfound - looks good in the image you attached.  Did you implement it?  Doesn't show on the live site...

**Comment by chrisguindon** [comment] 2019-07-31 17:49
@rickoco The PR was merged a few seconds ago. Should be on the website soon!

**Comment by autumnfound** [comment] 2019-07-31 18:34
This is live

**Comment by rickoco** [comment] 2019-07-31 20:18
sizing issue is still there...

![image](https://user-images.githubusercontent.com/2498391/62245105-cf976e00-b3ae-11e9-81e0-1bb77fa25039.png)

**Comment by autumnfound** [comment] 2019-07-31 20:20
@rickoco looks like its cached on your end. Could you try opening it in a private window? That should ignore the cache and get a fresh copy. I opened up a version of Chrome on my laptop and was unable to reproduce

![image](https://user-images.githubusercontent.com/23018241/62245210-184f2700-b3af-11e9-8f13-a6c2a044c145.png)

**Comment by chrisguindon** [comment] 2019-08-01 13:07
@rickoco  the page looks fine here:

http://quirktools.com/screenfly/#u=https%3A//www.osdforum.org/&w=1440&h=900&a=1

Closing this issue.

**Closed by chrisguindon** 2019-08-01 13:07 UTC

**Comment by rickoco** [comment] 2019-08-01 13:48
I tried hard refresh several times before re-opening the issue.  All good now.  Thanks.
